# -*- coding: utf-8 -*-
"""Untitled1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1KyuDR8Bj7AKDhLIeiv73moPr6OTLyeA4
"""

nome = input("digite seu primeiro nome: ").capitalize()
print(nome)

nome = input("digite seu primeiro nome: ").capitalize()
sobrenome = input("digite seu sobrenome: ").capitalize()
print(nome,sobrenome)

print("x     x\n x   x\n  x x\n   x\n  x x\n x   x\nx     x")

z=int(input("dia do aniversário: "))
x=input("mês do aniversário: ")
a=int(input("dia de hj: "))
b=input("mês de hj: ")
if x == "janeiro" or x == "1":
  m=0
elif x == "fevereiro" or x == "2":
  m=31
elif x == "março" or x == "3":
  m=59
if x == "abril" or x == "4":
  m=90
if x == "maio" or x == "5":
  m=120
if x == "junho" or x == "6":
  m=151
if x == "julho" or x == "7":
  m=181
if x == "agosto" or x == "8":
  m=212
if x == "setempro" or x == "9":
  m=242
if x == "outubro" or x == "10":
  m=273
if x == "novembro" or x == "11":
  m=303
if x == "dezembro" or x == "12":
  m=334
if b == "janeiro" or b == "1":
  d=0
if b == "fevereiro" or b == "2":
  d=31
if b == "março" or b == "3":
  d=59
if b == "abril" or b == "4":
  d=90
if b == "maio" or b == "5":
  d=120
if b == "junho" or b == "6":
  d=151
if b == "julho" or b == "7":
  d=181
if b == "agosto" or b == "8":
  d=212
if b == "setempro" or b == "9":
  d=242
if b == "outubro" or b == "10":
  d=273
if b == "novembro" or b == "11":
  d=303
if b == "dezembro" or b == "12":
  d=334
h = int(z+m)-int(a+d)
print(h)
if h > 0:
  print("faltam:",h,"dia(s) pro seu anivérsario")
if h < 0:
  print("faz",-h,"dia(s) desde o seu aniversário")
if h==0:
  print("hj é a por-- do seu aniversário. pq vc ta querendo saber isso. caso vc ainda queira saber. FALTAM 365 PRO DIA QUE SUA MÃE TE PARIU")

P=input("preço: ")
print("então...  \ngostei de vc    \nvo faze um preço de amigo pra tu")
D = float(P)*float(0.8)
d = float(P)*float(0.2)
print(float(D),"oq tu acha?\nvai economizar",float
 (d),"conto")

P=input("preço: ")
N=input("quanto de desconto vc quer negociar:")
print("então...  \ngostei de vc e te achei um eximio negociador   \nvo faze um preço de amigo pra tu")
D = float(P)*float(100-float(N))/float(100)
d = float(P)*float(N)/float(100)
print(float(D),"conto ent?\nta",float(d),"mais barato")

p=input("primeiro: ")
s=input("segundo: ")
t=input("terceiro: ")
M=(float(p)+float(t)+float(s))/float(3)
print(float(M))

p=input("primeiro: ")
s=input("segundo: ")
t=input("terceiro: ")
q=input("quarto: ")
mg=(float(q)*float(t)*float(s)*float(p))**float(0.25)
mh=float(4)/(float(p)**float(-1)+float(s)**float(-1)+float(t)**float(-1)+float(q)**float(-1))
M=(float(p)+float(t)+float(s)+float(q))/float(4)
print("média aritmética:",M)
print("média geométrica:",mg)
print("média harmonica:",mh)

import math
print("Digite 4 números reais:")
n1 = float(input("Número 1: "))
n2 = float(input("Número 2: "))
n3 = float(input("Número 3: "))
n4 = float(input("Número 4: "))

numeros = [n1, n2, n3, n4]

media = sum(numeros) / len(numeros)

variancia = sum((x - media) ** 2 for x in numeros) / len(numeros)

desvio_padrao = math.sqrt(variancia)

print(f"\nMédia aritmética: {media:.2f}")
print(f"Variância: {variancia:.2f}")
print(f"Desvio padrão: {desvio_padrao:.2f}")

primeiro = int(input("Digite o primeiro número: "))
segundo = int(input("Digite o segundo número: "))
terceiro = int(input("Digite o terceiro número: "))
print (f"O maior número é {max(primeiro, segundo, terceiro)}")
print (f"O menor número é {min(primeiro, segundo, terceiro)}")

primeiro = int(input("Digite o primeiro número: "))
segundo = int(input("Digite o segundo número: "))
terceiro = int(input("Digite o terceiro número: "))
print (f"em ordem crescente: {sorted([primeiro, segundo, terceiro])}")
print (f"em ordem decrescente: {sorted([primeiro, segundo, terceiro], reverse=True)}")

lista = input('digite seu texto separado por espaços: ').split(" ")
lista.sort()
print(lista)

genero = input("Digite o seu gênero (masuclino/feminino): ").strip().lower()
idade = int(input("Digite a sua idade: "))
peso = float(input("Digite o seu peso em kg: "))
altura = float(input("Digite a sua altura em cm: "))
if genero == "masculino" or genero == "m":
    TMB = (66.47 + (13.75 * peso ) + (5.003 * altura) - (6.755 * idade))
elif genero == "feminino" or genero == "f":
    TMB = (655.09 + (9.563 * peso) + (1.85 * altura) - (4.676 * idade))
else:
    print("Gênero inválido")
    exit()
print (f"Taxa Metabólica Basal: {TMB:.2f} kcal/dia")

numero = int(input("Digite um número inteiro: "))
for i in range(1, 11):
    resultado = numero * i
    print(f"{numero} x {i} = {resultado}")